"""Teacher-owned reference DAG for the class Airflow instance.

Purpose: guarantee the shared scheduler always has at least one DAG to
parse (so the DAGs list is never empty and the UI renders correctly
before any student has pushed their first PR) and give students a live
DAG to inspect for the Chapter 8 "read-only" etiquette step.

Do not edit this file unless you are the teacher. Students add DAGs
under ``dags/<yourname>/`` instead.
"""

from datetime import datetime

from airflow.sdk import dag, task


@dag(
    dag_id="class_demo_hello",
    schedule="@daily",
    start_date=datetime(2026, 1, 1),
    catchup=False,
    tags=["class-demo", "teacher", "week12"],
)
def class_demo_hello():
    @task()
    def greet() -> str:
        return "hello from the shared class Airflow"

    @task()
    def announce(message: str) -> None:
        print(f"[class-demo] {message}")

    announce(greet())


class_demo_hello()
